vich_uploader:
    db_driver: orm

    mappings:
                # Mapping pour l'image des produits
        produits_image:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/public/images/produits'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

                # Mapping pour les images des catégories
        categories_image:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    metadata:
        type: attribute
